name:                simpleFFT
version:             0.1.0.0
github:              "josephmckinsey/simpleFFT"
license:             BSD3
author:              "Joseph McKinsey"
maintainer:          "josephmckinsey2@gmail.com"
copyright:           "2018 Joseph McKinsey"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/josephmckinsey/simpleFFT#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  simpleFFT-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - simpleFFT

tests:
  simpleFFT-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - simpleFFT
